// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	NewsArticles       string
	NewsArticlesTopics string
	Topics             string
}{
	NewsArticles:       "news_articles",
	NewsArticlesTopics: "news_articles_topics",
	Topics:             "topics",
}
