version: '3.8'

services:
  app:
    build: ./misc/tools/reflex
    container_name: news_service_app
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app

  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5